  socket_host: "localhost"
  socket_port: 8017
  http:
    enabled: true
    port: 8018
  ws:
    enabled: true
    port: 8019
  storage_token: "12345"
  trusted_validators: ["15ycVNQF21PzUBFuKXgpKdekFxoRkH4LFT","1Bit5YxmptszS8JUfF7w3jhuw3wBNdLrHV","1Eukku2F7FDM5M4DyC8CHdF31kiNro6ELz"]
  #trusted_validators: ["15ycVNQF21PzUBFuKXgpKdekFxoRkH4LFT","1Bit5YxmptszS8JUfF7w3jhuw3wBNdLrHV"]
  sleep: 5
  storage_url: "http://sai-storage:8801"
  storage_email: "ddd@mial.com"
  storage_password: "fdfsdf"
  saiBTC_address: "http://sai-btc:3305"
  saiP2P_address: "http://sai-p2p:8112"
  saiVM1_address: "http://sai-vm1:8089"
  log_mode: "debug"
  saiProxy_address: "http://sai-p2p-proxy:8071"
  nodes_blacklist: ["18.218.186.169:9971"]
  initial_block_consensus_timeout_sec: 20
  skip_initializating: true